@startuml
class server.CollectionSaver {
- List<Product> products
+ List<Product> getProducts()
}
class innerClasses.Coordinates {
- double x
- Float y
+ void setX(double)
+ {static} boolean checkX(double)
+ void setY(Float)
+ {static} boolean checkY(Float)
+ double getX()
+ Float getY()
+ String toString()
}
class servCommands.FilterLessThanOwner {
+ void execute(ProductCollection,Object[],Server)
}
class servCommands.AverageOfPrice {
+ void execute(ProductCollection,Object[],Server)
}
class commandValidates.ValClear {
+ void validate(Scanner,String[],boolean,Client)
}
enum enums.Country {
+  UNITED_KINGDOM
+  USA
+  SPAIN
+  ITALY
+  NORTH_KOREA
+  UZBEK
}
class servCommands.AddIfMin {
+ void execute(ProductCollection,Object[],Server)
}
class commandValidates.ValWrite {
+ void validate(Scanner,String[],boolean,Client)
}
class commandValidates.ValRemoveLower {
+ void validate(Scanner,String[],boolean,Client)
}
class servCommands.Write {
+ void execute(ProductCollection,Object[],Server)
}
interface commandValidates.ValCommand {
~ void validate(Scanner,String[],boolean,Client)
}
class commandValidates.ValFilterStartsWithName {
+ void validate(Scanner,String[],boolean,Client)
}
class commandValidates.ValUpdate {
+ void validate(Scanner,String[],boolean,Client)
}
class commandValidates.ValHelp {
+ void validate(Scanner,String[],boolean,Client)
}
enum enums.UnitOfMeasure {
+  KILOGRAMS
+  SQUARE_METERS
+  GRAMS
}
class client.ProductCli {
- String name
- Coordinates coordinates
- Float price
- UnitOfMeasure unitOfMeasure
- Person owner
+ int compareTo(ProductCli)
+ String toString()
+ void setName(String)
+ {static} boolean checkName(String)
+ void setCoordinates(Coordinates)
+ void setOwner(Person)
+ void setPrice(Float)
+ {static} boolean checkPrice(Float)
+ void setUnitOfMeasure(UnitOfMeasure)
+ Float getPrice()
+ String getName()
+ Person getOwner()
+ Coordinates getCoordinates()
+ UnitOfMeasure getUnitOfMeasure()
+ {static} ProductCli createProduct(Scanner,boolean)
+ {static} boolean checkProduct(ProductCli)
}
enum enums.EyeColor {
+  GREEN
+  WHITE
+  BROWN
}
class commandValidates.ValShow {
+ void validate(Scanner,String[],boolean,Client)
}
class commandValidates.ValAdd {
+ void validate(Scanner,String[],boolean,Client)
}
class servCommands.Add {
+ void execute(ProductCollection,Object[],Server)
}
interface servCommands.Command {
~ void execute(ProductCollection,Object[],Server)
}
class server.Product {
- long id
- String name
- Coordinates coordinates
- ZonedDateTime creationDate
- Float price
- UnitOfMeasure unitOfMeasure
- Person owner
+ int compareTo(Product)
+ String toString()
+ void setName(String)
+ {static} boolean checkName(String)
+ void setCoordinates(Coordinates)
+ void setOwner(Person)
+ void setPrice(Float)
+ {static} boolean checkPrice(Float)
+ void setUnitOfMeasure(UnitOfMeasure)
+ void setId(long)
+ long getId()
+ Float getPrice()
+ String getName()
+ Person getOwner()
+ Coordinates getCoordinates()
+ UnitOfMeasure getUnitOfMeasure()
+ ZonedDateTime getCreationDate()
+ {static} boolean checkProduct(Product)
}
class client.CommandReader {
- boolean isFileReading
- {static} HashMap<String,ValCommand> commands
+ {static} void readCommands(Scanner,boolean,Client)
}
class servCommands.Show {
+ void execute(ProductCollection,Object[],Server)
}
class servCommands.Help {
+ void execute(ProductCollection,Object[],Server)
}
class servCommands.Save {
+ void execute(ProductCollection)
}
class servCommands.FilterStartsWithName {
+ void execute(ProductCollection,Object[],Server)
}
class servCommands.Info {
+ void execute(ProductCollection,Object[],Server)
}
class commandValidates.ValInfo {
+ void validate(Scanner,String[],boolean,Client)
}
class commandValidates.ValExecuteScript {
- int nesting
- Scanner[] previousScanners
- String readScript(Path)
- void saveScanner(Scanner)
+ void validate(Scanner,String[],boolean,Client)
}
enum enums.HairColor {
+  GREEN
+  BLACK
+  ORANGE
+  WHITE
}
class server.Server {
- int port
- SocketChannel sock
- ServerSocketChannel serv
- Scanner scanner
- String message
- ByteArrayOutputStream byteArrayOutputStream
- ObjectOutputStream objectOutputStream
+ boolean createConnection()
+ boolean serverWaiting()
+ void executeServCommand(ProductCollection)
+ void getCommand(ProductCollection)
+ void executeCommand(byte[],ProductCollection)
+ void addMessage(String)
+ byte[] serializeMessage(String)
+ void sendMessage()
}
class commandValidates.ValRemoveGreater {
+ void validate(Scanner,String[],boolean,Client)
}
class commandValidates.ValAddIfMin {
+ void validate(Scanner,String[],boolean,Client)
}
class servCommands.RemoveGreater {
+ void execute(ProductCollection,Object[],Server)
}
class client.Client {
- int port
- Socket sock
- OutputStream os
- InputStream is
+ boolean createConnection()
- byte[] serialize(Command,Object[])
+ void sendCommand(Command,Object[])
- String deserialize(byte[])
+ void catchResult()
}
class commandValidates.ValExit {
+ void validate(Scanner,String[],boolean,Client)
}
class commandValidates.ValAverageOfPrice {
+ void validate(Scanner,String[],boolean,Client)
}
class client.Main {
+ {static} void main(String[])
}
class commandValidates.ValFilterLessThanOwner {
+ void validate(Scanner,String[],boolean,Client)
}
class commandValidates.ValRemoveByID {
+ void validate(Scanner,String[],boolean,Client)
}
class innerClasses.Month {
- {static} HashMap<String,String> mounths
+ {static} String getMounthTranslation(String)
}
class servCommands.RemoveLower {
+ void execute(ProductCollection,Object[],Server)
}
class servCommands.Clear {
+ void execute(ProductCollection,Object[],Server)
}
class innerClasses.Person {
- String name
- String passportID
- EyeColor eyeColor
- HairColor hairColor
- Country nationality
+ void setName(String)
+ {static} boolean checkName(String)
+ void setPassportID(String)
+ {static} boolean checkPassportId(String)
+ void setEyeColor(EyeColor)
+ void setHairColor(HairColor)
+ void setNationality(Country)
+ String getName()
+ Country getNationality()
+ EyeColor getEyeColor()
+ HairColor getHairColor()
+ String getPassportID()
+ String toString()
+ int compareTo(Person)
+ {static} Person createPerson(Scanner,boolean)
}
class servCommands.Update {
+ void execute(ProductCollection,Object[],Server)
}
class servCommands.RemoveByID {
+ void execute(ProductCollection,Object[],Server)
}
class server.ProductCollection {
- LinkedHashSet<Product> products
- HashSet<Long> ID
- Date Creation_date
- String readPath()
- String readFile(String)
- List<Product> convertStringToCollection(String)
+ List<Product> getProducts()
+ void addProduct(Product)
+ void removeProduct(long)
+ void removeProducts(Collection<Product>)
+ Date getDate()
+ int getLen()
+ void clearCollection()
+ Product getMinProduct()
+ long MakeId()
+ HashSet<Long> getID()
}
class server.Main {
+ {static} void main(String[])
+ {static} void communictate(ProductCollection,Server)
}


java.io.Serializable <|.. innerClasses.Coordinates
servCommands.Command <|.. servCommands.FilterLessThanOwner
servCommands.Command <|.. servCommands.AverageOfPrice
commandValidates.ValCommand <|.. commandValidates.ValClear
servCommands.Command <|.. servCommands.AddIfMin
commandValidates.ValCommand <|.. commandValidates.ValWrite
commandValidates.ValCommand <|.. commandValidates.ValRemoveLower
servCommands.Command <|.. servCommands.Write
commandValidates.ValCommand <|.. commandValidates.ValFilterStartsWithName
commandValidates.ValCommand <|.. commandValidates.ValUpdate
commandValidates.ValCommand <|.. commandValidates.ValHelp
client.Comparable <|.. client.ProductCli
java.io.Serializable <|.. client.ProductCli
commandValidates.ValCommand <|.. commandValidates.ValShow
commandValidates.ValCommand <|.. commandValidates.ValAdd
servCommands.Command <|.. servCommands.Add
java.io.Serializable <|-- servCommands.Command
server.Comparable <|.. server.Product
servCommands.Command <|.. servCommands.Show
servCommands.Command <|.. servCommands.Help
servCommands.Command <|.. servCommands.FilterStartsWithName
servCommands.Command <|.. servCommands.Info
commandValidates.ValCommand <|.. commandValidates.ValInfo
commandValidates.ValCommand <|.. commandValidates.ValExecuteScript
commandValidates.ValCommand <|.. commandValidates.ValRemoveGreater
commandValidates.ValCommand <|.. commandValidates.ValAddIfMin
servCommands.Command <|.. servCommands.RemoveGreater
commandValidates.ValCommand <|.. commandValidates.ValExit
commandValidates.ValCommand <|.. commandValidates.ValAverageOfPrice
commandValidates.ValCommand <|.. commandValidates.ValFilterLessThanOwner
commandValidates.ValCommand <|.. commandValidates.ValRemoveByID
java.io.Serializable <|.. innerClasses.Month
servCommands.Command <|.. servCommands.RemoveLower
servCommands.Command <|.. servCommands.Clear
innerClasses.Comparable <|.. innerClasses.Person
java.io.Serializable <|.. innerClasses.Person
servCommands.Command <|.. servCommands.Update
servCommands.Command <|.. servCommands.RemoveByID
@enduml